import type { FieldConfig, SchemeConfig } from "@/lib/domain";
export const commonFields: FieldConfig[] = [
  {
    key: "fullName",
    label: "Full name",
    section: "Personal information",
    type: "text",
    required: true,
    help: "Use the name on your category certificate.",
  },
  {
    key: "dob",
    label: "Date of birth",
    section: "Personal information",
    type: "date",
    required: true,
  },
  {
    key: "gender",
    label: "Gender",
    section: "Personal information",
    type: "select",
    required: true,
    options: ["Female", "Male", "Other", "Prefer not to say"],
  },
  {
    key: "category",
    label: "Category",
    section: "Personal information",
    type: "select",
    required: true,
    options: ["Scheduled Tribe", "Other"],
  },
  {
    key: "email",
    label: "Email address",
    section: "Personal information",
    type: "email",
    required: true,
  },
  {
    key: "phone",
    label: "Mobile number",
    section: "Personal information",
    type: "tel",
    required: true,
  },
  {
    key: "state",
    label: "Domicile state",
    section: "Personal information",
    type: "select",
    required: true,
    options: [
      "Jharkhand",
      "Odisha",
      "Chhattisgarh",
      "Madhya Pradesh",
      "Maharashtra",
      "Rajasthan",
      "Assam",
      "Meghalaya",
    ],
  },
  {
    key: "district",
    label: "District",
    section: "Personal information",
    type: "text",
    required: true,
  },
  {
    key: "familyIncome",
    label: "Annual family income (INR)",
    section: "Academic & financial details",
    type: "number",
    required: true,
  },
  {
    key: "academicScore",
    label: "Academic score (%)",
    section: "Academic & financial details",
    type: "number",
    required: true,
    help: "Enter your percentage, not CGPA.",
  },
  {
    key: "institution",
    label: "Institution",
    section: "Academic & financial details",
    type: "text",
    required: true,
  },
  {
    key: "course",
    label: "Course",
    section: "Academic & financial details",
    type: "select",
    required: true,
    options: ["PhD", "MPhil", "Masters"],
  },
  {
    key: "applicationYear",
    label: "Application year",
    section: "Academic & financial details",
    type: "number",
    required: true,
  },
  {
    key: "bankLast4",
    label: "Bank account last 4 digits",
    section: "Academic & financial details",
    type: "text",
    required: true,
    help: "Prototype: enter only the last four digits. Do not enter a real account number.",
  },
  {
    key: "ifsc",
    label: "Bank IFSC / demo identifier",
    section: "Academic & financial details",
    type: "text",
    required: true,
  },
];
export const baseConfig: SchemeConfig = {
  fields: commonFields,
  documents: [
    {
      key: "category",
      label: "Tribe certificate",
      required: true,
      fields: ["fullName", "category", "certificateId"],
    },
    {
      key: "income",
      label: "Income certificate",
      required: true,
      fields: ["fullName", "familyIncome", "certificateId", "validUntil"],
    },
    {
      key: "academic",
      label: "Academic transcript",
      required: true,
      fields: ["fullName", "academicScore", "institution"],
    },
    {
      key: "domicile",
      label: "Domicile certificate",
      required: false,
      fields: ["fullName", "state"],
    },
  ],
  rules: [
    {
      id: "category",
      field: "category",
      operator: "=",
      value: "Scheduled Tribe",
      label: "Scheduled Tribe category",
    },
    {
      id: "income",
      field: "familyIncome",
      operator: "<=",
      value: 600000,
      label: "Annual income at most ₹6,00,000",
    },
    {
      id: "score",
      field: "academicScore",
      operator: ">=",
      value: 55,
      label: "Minimum academic score 55%",
    },
    {
      id: "age",
      field: "age",
      operator: "BETWEEN",
      value: [18, 35],
      label: "Age between 18 and 35",
    },
  ],
  weights: { academic: 70, income: 20, research: 10 },
  quota: 12,
  stateQuotas: {},
  renewalMinScore: 55,
  deficiencyDays: 14,
  confidenceThreshold: 80,
};
export const demoSchemes = [
  {
    id: "nfst",
    code: "NFST",
    name: "National Fellowship for ST Students",
    description:
      "Support your research journey. A configurable demonstration inspired by the National Fellowship for Scheduled Tribe students.",
    type: "Research fellowship",
    award: 37200,
    deadline: "2026-12-31",
    config: {
      ...baseConfig,
      fields: [
        ...commonFields,
        {
          key: "researchTitle",
          label: "Research title",
          section: "Research proposal",
          type: "text" as const,
          required: true,
        },
        {
          key: "supervisor",
          label: "Research supervisor",
          section: "Research proposal",
          type: "text" as const,
          required: true,
        },
        {
          key: "researchScore",
          label: "Research assessment score (%)",
          section: "Research proposal",
          type: "number" as const,
          required: true,
          help: "Demonstration assessment score; verified by an officer.",
        },
      ],
      rules: [
        ...baseConfig.rules,
        {
          id: "course",
          field: "course",
          operator: "IN" as const,
          value: ["PhD", "MPhil"],
          label: "Research course",
        },
      ],
    },
  },
  {
    id: "nos",
    code: "NOS",
    name: "National Overseas Scholarship",
    description:
      "Take your education across borders. A configurable demonstration inspired by the National Overseas Scholarship for ST students.",
    type: "Overseas scholarship",
    award: 1500000,
    deadline: "2026-11-30",
    config: {
      ...baseConfig,
      quota: 8,
      weights: { academic: 80, income: 20, research: 0 },
      fields: [
        ...commonFields,
        {
          key: "university",
          label: "Overseas university",
          section: "Overseas study",
          type: "text" as const,
          required: true,
        },
        {
          key: "country",
          label: "Destination country",
          section: "Overseas study",
          type: "text" as const,
          required: true,
        },
        {
          key: "offerStatus",
          label: "Admission offer",
          section: "Overseas study",
          type: "select" as const,
          required: true,
          options: ["Unconditional", "Conditional", "Awaiting offer"],
        },
      ],
      documents: [
        ...baseConfig.documents,
        {
          key: "admission",
          label: "University offer letter",
          required: true,
          fields: ["fullName", "university"],
        },
      ],
      rules: [
        ...baseConfig.rules,
        {
          id: "offer",
          field: "offerStatus",
          operator: "=" as const,
          value: "Unconditional",
          label: "Unconditional admission offer",
        },
      ],
    },
  },
];
